version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ../admin-panel/dist:/app/admin-dist
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: elysiadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
